on:
  push:
    paths:
      - 'routing-app/dist/**'

name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: 195.35.49.175
        username: u219389025
        password: ?mXWXqqVz8JGTM%
        local-dir: "routing-app/dist/"
